sudo: required
dist: trusty
language: node_js
node_js: stable

notifications:
  email: false
  
cache:
  directories: node_modules

addons:
apt:
  sources:
    - google-chrome

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install coveralls
- npm install
- ng build

script: ng test --watch=false --code-coverage

after_success: 'npm run coveralls'